// UPPERCASE ENGLISH COMMENTS PROVIDED FOR CORE PLATFORM TIER LIMITS
// ARCHITECTED TO PROVIDE DEFAULT FALLBACK CONFIGURATIONS FOR NEW TENANTS

export const ROLE_LIMITS = {
  PROJECT: 1, // DEFAULT FREE TIER PROJECT LIMIT
  FIELD_MANAGER: 2, // DEFAULT FREE TIER FIELD MANAGER LIMIT
  OFFICE_ADMIN: 1, // DEFAULT FREE TIER OFFICE ADMIN LIMIT
  ACCOUNT_MANAGER: 1, // DEFAULT FREE TIER ACCOUNT MANAGER LIMIT
};
